#!/bin/bash

# Add PPAs

add-apt-repository --yes ppa:nilarimogard/webupd8
add-apt-repository --yes ppa:webupd8team/java
add-apt-repository --yes ppa:jconti/recent-notifications
add-apt-repository --yes ppa:linrunner/tlp
add-apt-repository --yes ppa:jfi/ppa
add-apt-repository --yes ppa:libreoffice/libreoffice-5-4

# upgrade System

apt update
apt -y upgrade
apt -y dist-upgrade
apt -y autoremove
apt autoclean

# Install Additional Packages

apt install -y preload ubuntu-tweak aptitude acpi unity-tweak-tool mc ubuntu-restricted-extras ubuntu-restricted-addons fping gdebi dconf-tools whois ncdu nmap guake mc tlp tlp-rdw tp-smapi-dkms acpi-call-dkms psensor cpufrequtils indicator-cpufreq hddtemp lm-sensors psensor oracle-java9-installer ubuntu-wallpapers-karmic ubuntu-wallpapers-lucid ubuntu-wallpapers-maverick ubuntu-wallpapers-natty ubuntu-wallpapers-oneiric ubuntu-wallpapers-precise ubuntu-wallpapers-quantal ubuntu-wallpapers-raring ubuntu-wallpapers-saucy ssh dconf-tools plymouth-theme-solar whois ncdu nmap guake

# Unhide Startup Applications

sed -i 's/NoDisplay=true/NoDisplay=false/g' /etc/xdg/autostart/*.desktop
