#!/bin/bash

# Add PPAs
add-apt-repository --yes ppa:webupd8team/java
add-apt-repository --yes ppa:libreoffice/libreoffice-5-4

# Add the GetDeb Repo

sh -c 'echo "deb http://archive.getdeb.net/ubuntu $(lsb_release -sc)-getdeb apps" >> /etc/apt/sources.list.d/getdeb.list'

wget -q -O - http://archive.getdeb.net/getdeb-archive.key | sudo apt-key add -

# Bring the system up-to-date

apt -y update
apt -y upgrade
apt -y dist-upgrade
apt -y autoremove
apt -y autoclean

# Install additional software

apt install -y dselect

dselect update

dpkg --set-selections < ./pkgs-basic-install.txt

apt-get dselect-upgrade -y

# Set Java JDK 9 as default

apt install -y oracle-java9-set-default

# Unhide startup programs
sed -i 's/NoDisplay=true/NoDisplay=false/g' /etc/xdg/autostart/*.desktop

# Disable Apport Deamon

mv /etc/default/apport /etc/default/apport.orig
cp ./apport /etc/default/
chmod 644 /etc/default/apport
