#!/bin/bash

## This script adds all necessary power management packages

# Add Repositories

add-apt-repository --yes ppa:linrunner/tlp # TLP Repository

add-apt-repository --yes ppa:jfi/ppa # Psensor Repository 

apt update 

## Install Power Manegement Tools

