#!/bin/bash

## This script adds all necessary power management packages

# Add Repositories

add-apt-repository --yes ppa:linrunner/tlp # TLP Repository

add-apt-repository --yes ppa:jfi/ppa # Psensor Repository 

apt update 

Install Power Manegement Tools

apt -y install acpi tlp tlp-rdw tp-smapi-dkms acpi-call-dkms psensor cpufrequtils indicator-cpufreq hddtemp lm-sensors psensor
